OnlineShop/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DomainModel;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly OnlineShopContext _context;

        public UsersController(OnlineShopContext context)
        {
            _context = context;
        }

        // GET: Admin/Users
        public async Task<IActionResult> Index()
        {
            var onlineShopContext = _context.Users.Include(u => u.UserType);
            return View(await onlineShopContext.ToListAsync());
        }

        // GET: Admin/Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.UserType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Admin/Users/Create
        public IActionResult Create()
        {
            ViewData["UserTypeId"] = new SelectList(_context.UserTypes, "Id", "Id");
            return View();
        }

        // POST: Admin/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserTypeId,FullName,Email,Password,MobileNumber,Address,CreateDate,CreateBy,EditDate,EditBy,IsDelete")] DomainModel.User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserTypes, "Id", "Id", user.UserTypeId);
            return View(user);
        }

        // GET: Admin/Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserTypes, "Id", "Id", user.UserTypeId);
            return View(user);
        }

        // POST: Admin/Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserTypeId,FullName,Email,Password,MobileNumber,Address,CreateDate,CreateBy,EditDate,EditBy,IsDelete")] DomainModel.User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserTypeId"] = new SelectList(_context.UserTypes, "Id", "Id", user.UserTypeId);
            return View(user);
        }

        // GET: Admin/Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.UserType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Admin/Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

OnlineShop/Areas/User/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DomainModel;

namespace OnlineShop.Areas.User.Controllers
{
    [Area("User")]
    public class OrdersController : Controller
    {
        private readonly OnlineShopContext _context;

        public OrdersController(OnlineShopContext context)
        {
            _context = context;
        }

        // GET: User/Orders
        public async Task<IActionResult> Index()
        {
            var onlineShopContext = _context.Orders.Include(o => o.User);
            return View(await onlineShopContext.ToListAsync());
        }

        // GET: User/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: User/Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: User/Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,OrderStaus,TotalPrice,CreateDate,CreateBy,EditDate,EditBy,IsDelete")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: User/Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: User/Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,OrderStaus,TotalPrice,CreateDate,CreateBy,EditDate,EditBy,IsDelete")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: User/Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: User/Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

OnlineShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DomainModel;
using ViewModel;
using Repository;

namespace OnlineShop.Controllers
{
    public class ProductsController : Controller
    {
        private int ProductCount = 6;
        private readonly IDataRepository<Product> _dataRepository;
        private readonly IDataRepository<Category> _categoryDdataRepository;
        private readonly ProductRepository _productRepository;
        private readonly ProductImagesRepository _productImageDataRepository;

        public ProductsController(
              IDataRepository<Product> dataRepository
            , IDataRepository<Category> categoryDdataRepository
            , ProductRepository productRepository
            , ProductImagesRepository productImageDataRepository)
        {
            _dataRepository = dataRepository;
            _categoryDdataRepository = categoryDdataRepository;
            _productRepository = productRepository;
            _productImageDataRepository = productImageDataRepository;

        }

        [HttpGet]
        public IActionResult PreviewProducts(int CategoryId)
        {
            List<PreviewProductViewModel> products = new List<PreviewProductViewModel>();
            List<Product> models = _productRepository.GetByCategory(CategoryId, ProductCount).ToList();
            foreach (Product item in models)
            {
                PreviewProductViewModel PreviewProduct = new PreviewProductViewModel();
                PreviewProduct.Id = item.Id;
                PreviewProduct.Title = item.Title;
                PreviewProduct.Price = item.Price;
                if(_productImageDataRepository.GetByProductId(item.Id)!=null)
                    PreviewProduct.MainImageTitle = "\\images\\products\\main\\" + _productImageDataRepository.GetByProductId(item.Id).Title;

                products.Add(PreviewProduct);
            }
            IEnumerable<PreviewProductViewModel> PreviewProducts = products;
            return Ok(PreviewProducts);
        }

        // GET: products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product entity = _dataRepository.Get((long)id);
            ProductDetailsViewModel model = new ProductDetailsViewModel();
            model.CategoryId = entity.CategoryId;
            model.Id = entity.Id;
            model.Title = entity.Title;
            model.Price = entity.Price;
            model.Description = entity.Description;
            model.MainImageTitle = "\\images\\products\\main\\" + _productImageDataRepository.GetByProductId(model.Id).Title;
            model.CategoryTitle = _categoryDdataRepository.Get(model.CategoryId).Title;
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        public IActionResult List(int CategoryId)
        {
            List<PreviewProductViewModel> products = new List<PreviewProductViewModel>();
            List<Product> models = _productRepository.GetByCategory(CategoryId).ToList();
            foreach (Product item in models)
            {
                PreviewProductViewModel PreviewProduct = new PreviewProductViewModel();
                PreviewProduct.Id = item.Id;
                PreviewProduct.Title = item.Title;
                PreviewProduct.Price = item.Price;
                if (_productImageDataRepository.GetByProductId(item.Id) != null)
                    PreviewProduct.MainImageTitle = "\\images\\products\\main\\" + _productImageDataRepository.GetByProductId(item.Id).Title;

                products.Add(PreviewProduct);
            }
            IEnumerable<PreviewProductViewModel> PreviewProducts = products;
            ViewBag.categoryTitle = _categoryDdataRepository.Get(CategoryId).Title; ;
            return View(PreviewProducts);
        }
    }
}

OnlineShop/Areas/Admin/Views/Products/Create.cshtml
@model DomainModel.Product
@addTagHelper *, Kendo.Mvc
@using Kendo.Mvc.UI

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "افزودن";
}

@section AddToHead{
}
<div class="row" style="margin: 0 15px 0 15px; direction:rtl;">
    <!--Menu-->
    <div class="col col-lg-3 col-sm-12">
        <div class="box">
            <div class="row">
                <div class="col col-lg-2">
                    <img src="~/images/panel/user.svg" alt="user-photo">
                </div>
                <div class="col col-lg-10">
                    <p class="bold">مدیر سیستم</p>
                </div>
            </div>
            <div class="line"></div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category-active.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Products" class="menu-item-text active">محصولات</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Categories" class="menu-item-text">دسته‌بندی‌ها</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Users" class="menu-item-text">کاربران</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Orders" class="menu-item-text">سفارش‌ها</a>
                </div>
            </div>
            <div class="line menu-item"></div>
            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/logout.svg " class="menu-item-image" alt="logout">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="SignIn" asp-controller="User" asp-area="" class="menu-item-text">خروج</a>
                </div>
            </div>
        </div>
    </div>

    <!--content-->
    <div class="col col-lg-9 col-sm-12">
        <div class="box">
            <div class="row mb-2">
                <div class="col col-lg-2 col-sm-6">
                    <p class="active">محصول جديد</p>

                </div>
                <div class="col col-lg-10 col-sm-6">
                    <a id="back" class="btn btn-outline-primary btn-new">بازگشت</a>
                </div>

            </div>
            <div class="line mb-4"></div>
            <p>مشخصات اصلي</p>
            <div class="row mb-4">
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">نام محصول</p>
                    <input id="Title" type="text" class="form-control mb-2" placeholder="نام محصول" required autofocus>

                </div>
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">دسته بندي</p>

                    @*<div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle dropdown-fa" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        انتخاب دسته‌بندي
                    </button>
                    <div class="dropdown-menu dropdown-fa" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item dropdown-fa">آرايشي</a>
                        <a class="dropdown-item dropdown-fa">مد</a>
                        <a class="dropdown-item dropdown-fa">خانه</a>
                    </div>
                </div>*@
                    @Html.DropDownList("Categories", ViewBag.Categories as SelectList, new { @id = "CategoryId", @class= "form-control mb-2" })

                </div>
            </div>
            <div class="row mb-4">
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">قيمت‌واحد <span>(تومان)</span></p>
                    <input id="Price" type="number" class="form-control mb-2" placeholder="قيمت‌واحد" required autofocus>

                </div>
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">تعداد‌ موجودي</p>
                    <input id="Quantity" type="number" class="form-control mb-2" placeholder="تعداد موجودي" required autofocus>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col col-lg-12 col-sm-12">
                    <p class="input-title">توضيحات</p>
                    <textarea class="form-control" rows="3" id="Description"></textarea>
                </div>
            </div>




            <div class="line mb-4"></div>
            <p>تصاوير كالا</p>
            @*<form method="post" action='@Url.Action("Basic_Usage_Submit")'>*@
            <div class="row mb-4">
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">تصوير اصلي</p>
                    <div class="demo-section k-content">
                        @(Html.Kendo().Upload()
                            .Name("MainImage")
                            .HtmlAttributes(new { aria_label = "files" })
                            .Multiple(false)
                            )
                    </div>
                </div>
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">ساير تصاوير</p>
                    @(Html.Kendo().Upload()
                            .Name("OtherImages")
                            .HtmlAttributes(new { aria_label = "files" })
                            .Multiple(true)
                            )
                </div>
            </div>
            @*</form>*@

            <div class="line mb-4"></div>
            <p>ساير مشخصات</p>
            <div class="row mb-4">
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">نام ويژگي</p>
                    <input type="text" class="form-control mb-2" placeholder="نام ويژگي" required autofocus>

                </div>
                <div class="col col-lg-6 col-sm-12">
                    <p class="input-title">مقدار ويژگي</p>
                    <input type="text" class="form-control mb-2" placeholder="مقدار ويژگي" required autofocus>
                </div>
            </div>


            <div class="row mb-4">
                <div class="col col-lg-6 col-sm-12">
                    <button id="Save" class="btn btn-success btn-block">ثبت</button>

                </div>
                <div class="col col-lg-6 col-sm-12">
                    <button class="btn btn-primary btn-block">انصراف</button>
                </div>
            </div>

        </div>

    </div>
</div>




<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
        $(document).ready(function () {
            $('#back').click(function () {
                window.location.href = "@Url.Action("Index","Products")";
            });

            $("#Save1").click(function () {

                var upload = $("#MainImage").data("kendoUpload"),
                    files = upload.getFiles()[0];

                console.log('files: ', files);

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Create", "Products")",
                    dataType: 'application/json; charset=utf-8',
                    data: {
                        'UserId': $("#UserId").val(),
                        'CategoryId': $("#CategoryId").val(),
                        'Title': $("#Title").val(),
                        'Quantity': $("#Quantity").val(),
                        'Price': $("#Price").val(),
                        'Description': $("#Description").val(),
                        'MainImage': files,
                    },
                    success: function () {
                        alert("ثبت با موفقیت انجام شد.");
                        window.location.href = "@Url.Action("Index", "Products")";
                    },
                    error: function () {
                        alert("خطایی رخ داده است.");
                        window.location.href = "@Url.Action("Index", "Products")";

                    },
                });
            });

            $("#Save").on("click", function (e) {
                e.preventDefault();

                // Append the desired file
                var formData = new FormData();
                var upload = $("#MainImage").getKendoUpload();
                var files = upload.getFiles();

                var otherUpload = $("#OtherImages").getKendoUpload();
                var otherFiles = otherUpload.getFiles();
                console.log('otherFiles: ', otherFiles)

                formData.append('CategoryId', $("#CategoryId").val());
                formData.append('Title', $("#Title").val());
                formData.append('Quantity', $("#Quantity").val());
                formData.append('Price', $("#Price").val());
                formData.append('Description', $("#Description").val());
                formData.append('MainImage', files[0].rawFile);
                formData.append('OtherImages', otherFiles);

                // Send the request
                $.ajax({
                    url: "@Url.Action("Create", "Products")",
                    type: 'POST',
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function () {
                        alert("ثبت با موفقیت انجام شد.");
                        $("#Title").val('');
                        $("#CategoryId").val('0');
                        $("#Price").val('');
                        $("#Quantity").val('');
                        $("#Description").val('');
                        var div = $("div").first();
                        $("div").last().text("scrollTop:" + div.scrollTop());
                    },
                    error: function () {
                        alert("خطایی رخ داده است.");

                    },
                });
            });

        });
</script>
}

OnlineShop/Areas/Admin/Views/Products/Delete.cshtml
@model ViewModel.ProductDetailsViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "جزئیات محصول";
}

<h1>مشاهده جزئیات محصول</h1>



<div class="row" style="margin: 0 15px 0 15px; direction:rtl;">
    <!--Menu-->
    <div class="col col-lg-3 col-sm-12">
        <div class="box">
            <div class="row">
                <div class="col col-lg-2">
                    <img src="~/images/panel/user.svg" alt="user-photo">
                </div>
                <div class="col col-lg-10">
                    <p class="bold">مدیر سیستم</p>
                </div>
            </div>
            <div class="line"></div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category-active.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Products" class="menu-item-text active">محصولات</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Categories" class="menu-item-text">دسته‌بندی‌ها</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Users" class="menu-item-text">کاربران</a>
                </div>
            </div>

            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/category.svg " class="menu-item-image" alt="products">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="Index" asp-controller="Orders" class="menu-item-text">سفارش‌ها</a>
                </div>
            </div>
            <div class="line menu-item"></div>
            <div class="row menu-item">
                <div class="col col-lg-2">
                    <img src="~/images/panel/logout.svg " class="menu-item-image" alt="logout">
                </div>
                <div class="col col-lg-10">
                    <a asp-action="SignIn" asp-controller="User" asp-area="" class="menu-item-text">خروج</a>
                </div>
            </div>
        </div>


    </div>
    <!--content-->
    <div class="col col-lg-9 col-sm-12">
        <div class="box">

            <div>
                <h4>جزئیات محصول</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CategoryTitle)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CategoryTitle)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Price)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Price)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Quantity)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Quantity)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.MainImageTitle)
                    </dt>
                    <dd class="col-sm-10">
                        <img id="main-image" src="@Html.DisplayFor(model => model.MainImageTitle)" class="product-main-image">

                    </dd>
                </dl>
            </div>
            <div>
                <form asp-action="DeleteById">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="حذف محصول" class="btn btn-danger" /> |
                    <a asp-action="Index">بازگشت به لیست</a>
                </form>
            </div>

        </div>

    </div>
</div>




<div>
</div>







  